<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Chapter 30. Exception Handling</title><link rel="stylesheet" type="text/css" href="docbook.css"/><link rel="stylesheet" type="text/css" href="css/jbossorg.css"/><meta name="generator" content="DocBook XSL Stylesheets V1.79.1"/><link rel="prev" href="ch29.html" title="Chapter 29. Responses using javax.ws.rs.core.Response"/><link rel="next" href="ch31.html" title="Chapter 31. Configuring Individual JAX-RS Resource Beans"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/></head><body><header><p id="title"><a href="http://www.jboss.org" class="site_href"><strong>JBoss.org</strong></a><a href="http://docs.jboss.org/" class="doc_href"><strong>Community Documentation</strong></a></p><ul class="docnav"><li class="previous"><a accesskey="p" href="ch29.html"><strong>Prev</strong></a></li><li class="next"><a accesskey="n" href="ch31.html"><strong>Next</strong></a></li></ul></header><section class="chapter" id="ExceptionHandling"><div class="titlepage"><div><div><h1 class="title">Chapter 30. Exception Handling</h1></div></div></div><div class="toc"><ul class="toc"><li><span class="sect1"><a href="ch30.html#ExceptionMappers">30.1. Exception Mappers</a></span></li><li><span class="sect1"><a href="ch30.html#builtinException">30.2. RESTEasy Built-in Internally-Thrown Exceptions</a></span></li><li><span class="sect1"><a href="ch30.html#ResteasyWebApplicationException">30.3. Resteasy WebApplicationExceptions</a></span></li><li><span class="sect1"><a href="ch30.html#overring_resteasy_exceptions">30.4. Overriding RESTEasy Builtin Exceptions</a></span></li></ul></div>
   

   <section class="sect1" id="ExceptionMappers"><div class="titlepage"><div><div><h2 class="title">30.1. Exception Mappers</h2></div></div></div>
   
   <p>

      ExceptionMappers are custom, application provided, components that can catch thrown application exceptions and
      write specific HTTP responses. They are classes annotated with @Provider and that implement this interface
   </p>
   <p>

      </p><pre><code class="no-highlight">
         package javax.ws.rs.ext;

         import javax.ws.rs.core.Response;

         /**
         * Contract for a provider that maps Java exceptions to
         * {@link javax.ws.rs.core.Response}. An implementation of this interface must
         * be annotated with {@link Provider}.
         *
         * @see Provider
         * @see javax.ws.rs.core.Response
         */
         public interface ExceptionMapper&lt;E&gt;
         {
            /**
            * Map an exception to a {@link javax.ws.rs.core.Response}.
            *
            * @param exception the exception to map to a response
            * @return a response mapped from the supplied exception
            */
            Response toResponse(E exception);
         }
      </code></pre><p>
   </p>
   <p>

      When an application exception is thrown it will be caught by the JAX-RS runtime. JAX-RS will then scan registered
      ExceptionMappers to see which one support marshalling the exception type thrown. Here is an example of
      ExceptionMapper
   </p>
   <p>

      </p><pre><code class="no-highlight">

         @Provider
         public class EJBExceptionMapper implements ExceptionMapper&lt;javax.ejb.EJBException&gt;
         {
            public Response toResponse(EJBException exception) {
               return Response.status(500).build();
            }
         }
      </code></pre><p>
   </p>
   <p>

      You register ExceptionMappers the same way you do MessageBodyReader/Writers. By scanning for @Provider
      annotated classes, or programmatically through the
      ResteasyProviderFactory class.
   </p>
   <p>


   </p>
   </section>
   <section class="sect1" id="builtinException"><div class="titlepage"><div><div><h2 class="title">30.2. RESTEasy Built-in Internally-Thrown Exceptions</h2></div></div></div>
     
     <p>RESTEasy has a set of built-in exceptions that are thrown by it when it encounters errors during dispatching or marshalling.  They all
           revolve around specific HTTP error codes.  You can find them in RESTEasy's javadoc under the package org.jboss.resteasy.spi.  Here's
           a list of them:</p>
<div class="table" id="d5e2095"><div class="table-title">Table 30.1. </div><div class="table-contents">
<table style="border-collapse: collapse;border-top: 1px solid ; border-bottom: 1px solid ; "><colgroup><col/><col/><col/></colgroup><thead><tr><th style="border-right: 1px  ; border-bottom: 1px  ; ">Exception</th><th style="border-right: 1px  ; border-bottom: 1px  ; ">HTTP Code</th><th style="border-bottom: 1px  ; ">Description</th></tr></thead><tbody><tr><td style="border-right: 1px  ; border-bottom: 1px  ; ">ReaderException</td><td style="border-right: 1px  ; border-bottom: 1px  ; ">400</td><td style="border-bottom: 1px  ; ">All exceptions thrown from MessageBodyReaders are wrapped within this exception.  If there is no ExceptionMapper for the
wrapped exception or if the exception isn't a WebApplicationException, then resteasy will return a 400 code by default.</td></tr><tr><td style="border-right: 1px  ; border-bottom: 1px  ; ">WriterException</td><td style="border-right: 1px  ; border-bottom: 1px  ; ">500</td><td style="border-bottom: 1px  ; ">All exceptions thrown from MessageBodyWriters are wrapped within this exception.  If there is no ExceptionMapper for the
wrapped exception or if the exception isn't a WebApplicationException, then resteasy will return a 400 code by default.</td></tr><tr><td style="border-right: 1px  ; border-bottom: 1px  ; ">o.j.r.plugins.providers.jaxb.JAXBUnmarshalException</td><td style="border-right: 1px  ; border-bottom: 1px  ; ">400</td><td style="border-bottom: 1px  ; ">The JAXB providers throw this exception on reads.  They may be wrapping JAXBExceptions.  This class extends ReaderException</td></tr><tr><td style="border-right: 1px  ; border-bottom: 1px  ; ">o.j.r.plugins.providers.jaxb.JAXBMarshalException</td><td style="border-right: 1px  ; border-bottom: 1px  ; ">500</td><td style="border-bottom: 1px  ; ">The JAXB providers throw this exception on writes.  They may be wrapping JAXBExceptions.  This class extends WriterException</td></tr><tr><td style="border-right: 1px  ; border-bottom: 1px  ; ">ApplicationException</td><td style="border-right: 1px  ; border-bottom: 1px  ; ">N/A</td><td style="border-bottom: 1px  ; ">This exception wraps all exceptions thrown from application code.  It functions much in the same way as InvocationTargetException.
If there is an ExceptionMapper for wrapped exception, then that is used to handle the request.</td></tr><tr><td style="border-right: 1px  ; border-bottom: 1px  ; ">Failure</td><td style="border-right: 1px  ; border-bottom: 1px  ; ">N/A</td><td style="border-bottom: 1px  ; ">Internal RESTEasy.  Not logged</td></tr><tr><td style="border-right: 1px  ; border-bottom: 1px  ; ">LoggableFailure</td><td style="border-right: 1px  ; border-bottom: 1px  ; ">N/A</td><td style="border-bottom: 1px  ; ">Internal RESTEasy error.  Logged</td></tr><tr><td style="border-right: 1px  ; border-bottom: 1px  ; ">DefaultOptionsMethodException</td><td style="border-right: 1px  ; border-bottom: 1px  ; ">N/A</td><td style="border-bottom: 1px  ; ">If the user invokes HTTP OPTIONS and no JAX-RS method for it, RESTEasy provides a default behavior by throwing this exception.
This is only done if the property <code class="code">dev.resteasy.throw.options.exception</code> is set to true.</td></tr><tr><td style="border-right: 1px  ; ">UnrecognizedPropertyExceptionHandler</td><td style="border-right: 1px  ; ">400</td><td>A Jackson provider throws this exception when JSON data is determine to be invalid.</td></tr></tbody></table>
</div></div><br class="table-break"/>
</section>
<section class="sect1" id="ResteasyWebApplicationException"><div class="titlepage"><div><div><h2 class="title">30.3. Resteasy WebApplicationExceptions</h2></div></div></div>
   
   <p>Suppose a client at local.com calls the following resource method:</p>
   <pre><code class="no-highlight">
   @GET
   @Path("remote")
   public String remote() throws Exception {
      Client client = ClientBuilder.newClient();
      return client.target("http://third.party.com/exception").request().get(String.class);
   }
   </code></pre>
   <p>If the call to http://third.party.com returns a status code 3xx, 4xx, or 5xx, then the 
   <code class="classname">Client</code> is obliged by the JAX-RS
   specification to throw a <code class="classname">WebApplicationException</code>. Moreover, if the
   <code class="classname">WebApplicationException</code> contains a <code class="classname">Response</code>, which
   it normally would in RESTEasy, the server runtime is obliged by the JAX-RS specification to return that
   <code class="classname">Response</code>.
   As a result, information from the server at third.party.com, e.g., headers and body, will get sent back to
   local.com. The problem is that that information could be, at best, meaningless to the client
   and, at worst, a security breach.</p>

   <p>RESTEasy has a solution that works around the problem and still conforms to the JAX-RS specification.
   In particular, for each <code class="classname">WebApplicationException</code> it defines a new subclass:</p>

<pre><code class="no-highlight">
WebApplicationException
+-ResteasyWebApplicationException
+-ClientErrorException
| +-ResteasyClientErrorException
| +-BadRequestException
| | +-ResteasyBadRequestException
| +-ForbiddenException
| | +-ResteasyForbiddenException
| +-NotAcceptableException
| | +-ResteasyNotAcceptableException
| +-NotAllowedException
| | +-ResteasyNotAllowedException
| +-NotAuthorizedException
| | +-ResteasyNotAuthorizedException
| +-NotFoundException
| | +-ResteasyNotFoundException
| +-NotSupportedException
| | +-ResteasyNotSupportedException
+-RedirectionException
| +-ResteasyRedirectionException
+-ServerErrorException
| +-ResteasyServerErrorException
| +-InternalServerErrorException
| | +-ResteasyInternalServerErrorException
| +-ServiceUnavailableException
| | +-ResteasyServiceUnavailableException
</code></pre>

    <p>The new <code class="classname">Exception</code>s play the same role as the original ones,
   but RESTEasy treats them slightly differently. When a <code class="classname">Client</code> detects
   that it is running in the context of a resource method, it will throw one of the new
   <code class="classname">Exception</code>s. However, instead of storing the original <code class="classname">Response</code>,
   it stores a "sanitized" version of the <code class="classname">Response</code>, in which only the status and
   the Allow and Content-Type headers are preserved. The original <code class="classname">WebApplicationException</code>,
   and therefore the original <code class="classname">Response</code>, can be accessed in one of two ways:</p>
   
   <pre><code class="no-highlight">
// Create a NotAcceptableException.
NotAcceptableException nae = new NotAcceptableException(Response.status(406).entity("ooops").build());

// Wrap the NotAcceptableException in a ResteasyNotAcceptableException.
ResteasyNotAcceptableException rnae = (ResteasyNotAcceptableException) WebApplicationExceptionWrapper.wrap(nae);

// Extract the original NotAcceptableException using instance method.
NotAcceptableException nae2 = rnae.unwrap();
Assert.assertEquals(nae, nae2);

// Extract the original NotAcceptableException using class method.
NotAcceptableException nae3 = (NotAcceptableException) WebApplicationExceptionWrapper.unwrap(nae); // second way
Assert.assertEquals(nae, nae3);
   </code></pre>
   
   <p>Note that this change is intended to introduce a safe default behavior in the case that
   the <code class="classname">Exception</code> generated by the remote call is allowed to make its way up
   to the server runtime. It is considered a good practice, though, to catch the 
   <code class="classname">Exception</code> and treat it in some appropriate manner:</p>
   
<pre><code class="no-highlight">
   @GET
   @Path("remote/{i}")
   public String remote(@PathParam("i") String i) throws Exception {
      Client client = ClientBuilder.newClient();
      try {
         return client.target("http://remote.com/exception/" + i).request().get(String.class);
      } catch (WebApplicationException wae) {
         ...
      }
   }
</code></pre>

   <p><span class="bold"><strong>Note.</strong></span> While RESTEasy will default to the new, safer behavior, the original behavior can
   be restored by setting the configuration parameter "resteasy.original.webapplicationexception.behavior"
   to "true".</p>
</section>

<section class="sect1" id="overring_resteasy_exceptions"><div class="titlepage"><div><div><h2 class="title">30.4. Overriding RESTEasy Builtin Exceptions</h2></div></div></div>
   
   <p>You may override RESTEasy built-in exceptions by writing an ExceptionMapper for the exception.  For that matter, you can write an ExceptionMapper
   for any thrown exception including WebApplicationException</p>
</section>
</section><script type="text/javascript" src="highlight.js/highlight.pack.js"> </script><script type="text/javascript">hljs.initHighlightingOnLoad();</script><footer><ul class="docnav"><li class="previous"><a accesskey="p" href="ch29.html"><strong>Prev</strong>Chapter 29. Responses using javax.ws.rs.core.Resp...</a></li><li class="up"><a accesskey="u" href="#"><strong>Up</strong></a></li><li class="home"><a accesskey="h" href="index.html"><strong>Home</strong></a></li><li class="next"><a accesskey="n" href="ch31.html"><strong>Next</strong>Chapter 31. Configuring Individual JAX-RS Resourc...</a></li></ul></footer></body></html>